import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/header/Navbar";
import Sticky from "./components/Sticky";
export const metadata: Metadata = {
  title: "Sain Kanzlei Law Firm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Sticky />
        {children}
      </body>
    </html>
  );
}
